### ISSUE TITLE
error loading the checkpoint

### ISSUE THREAD

**Issue by unnamed333user** [IDEA-Research/UniPose#4]
Hi @yangjie-cv tks for updating your work. Iam running the inference_on_a_image.py file and meet this error:
![image](https://github.com/IDEA-Research/UniPose/assets/149768575/60ef5dae-4e12-4714-9c26-3e89a1c06393)
I also checked the number of layers in model and in the checkpoint. they are 1165 and 1015 respectively.
can you double check the code ? tks~

**Comment by yangjie-cv** [comment]
Hello, it appears that the error does not originate from the model itself. This is likely due to an incorrect instance prompt input. I kindly recommend following the provided comment for conducting the inference: 

python inference_on_a_image.py -c config/UniPose_SwinT.py -p weights/unipose_swint.pth -i image_you_want_to_test.jpg -o "dir you want to save the output" -t "person"

**Comment by unnamed333user** [comment]
tks, it worked (^^)
